export const MOCK_PROJECTS = [
  {
    id: 1,
    title: "1인 가구를 위한 식사 플랫폼 프로젝트 (단기간 프로젝트)",
    description: "참여 인원 : 인원 미정\n마감일 : 2026-01-01",
    tags: ["디자이너", "백엔드"],
    user: {
      name: "디자인 취준생",
      avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Molly",
    },
    thumbnail: null, // Grey box in image
    likes: 0,
    members: [1, 2, 3], // For +1 avatar display
  },
  {
    id: 2,
    title: "1인 가구를 위한 식사 플랫폼 프로젝트 (단기간 프로젝트)",
    description: "참여 인원 : 인원 미정\n마감일 : 2026-01-01",
    tags: ["디자이너", "백엔드"],
    user: {
      name: "디자인 취준생",
      avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sasha",
    },
    thumbnail: null,
    likes: 0,
    members: [1, 2, 3],
  },
  {
    id: 3,
    title: "1인 가구를 위한 식사 플랫폼 프로젝트 (단기간 프로젝트)",
    description: "참여 인원 : 인원 미정\n마감일 : 2026-01-01",
    tags: ["디자이너", "백엔드"],
    user: {
      name: "디자인 취준생",
      avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Leo",
    },
    thumbnail: null,
    likes: 0,
    members: [1, 2, 3],
  },
  {
    id: 4,
    title: "1인 가구를 위한 식사 플랫폼 프로젝트 (단기간 프로젝트)",
    description: "참여 인원 : 인원 미정\n마감일 : 2026-01-01",
    tags: ["디자이너", "백엔드"],
    user: {
      name: "디자인 취준생",
      avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Felix",
    },
    thumbnail: null,
    likes: 0,
    members: [1, 2, 3],
  },
  {
    id: 5,
    title: "1인 가구를 위한 식사 플랫폼 프로젝트 (단기간 프로젝트)",
    description: "참여 인원 : 인원 미정\n마감일 : 2026-01-01",
    tags: ["디자이너", "백엔드"],
    user: {
      name: "디자인 취준생",
      avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Aneka",
    },
    thumbnail: null,
    likes: 0,
    members: [1, 2, 3],
  },
  {
    id: 6,
    title: "1인 가구를 위한 식사 플랫폼 프로젝트 (단기간 프로젝트)",
    description: "참여 인원 : 인원 미정\n마감일 : 2026-01-01",
    tags: ["디자이너", "백엔드"],
    user: {
      name: "디자인 취준생",
      avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Bob",
    },
    thumbnail: null,
    likes: 0,
    members: [1, 2, 3],
  },
  {
    id: 7,
    title: "1인 가구를 위한 식사 플랫폼 프로젝트 (단기간 프로젝트)",
    description: "참여 인원 : 인원 미정\n마감일 : 2026-01-01",
    tags: ["디자이너", "백엔드"],
    user: {
      name: "디자인 취준생",
      avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jack",
    },
    thumbnail: null,
    likes: 0,
    members: [1, 2, 3],
  },
  {
    id: 8,
    title: "1인 가구를 위한 식사 플랫폼 프로젝트 (단기간 프로젝트)",
    description: "참여 인원 : 인원 미정\n마감일 : 2026-01-01",
    tags: ["디자이너", "백엔드"],
    user: {
      name: "디자인 취준생",
      avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Bear",
    },
    thumbnail: null,
    likes: 0,
    members: [1, 2, 3],
  },
  {
    id: 9,
    title: "1인 가구를 위한 식사 플랫폼 프로젝트 (단기간 프로젝트)",
    description: "참여 인원 : 인원 미정\n마감일 : 2026-01-01",
    tags: ["디자이너", "백엔드"],
    user: {
      name: "디자인 취준생",
      avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Cuddles",
    },
    thumbnail: null,
    likes: 0,
    members: [1, 2, 3],
  },
];
